[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Thomas Van den Bossche", email = "thomas.vandenbossche@odisee.be"}]
dynamic = ["version", "description"]
